[package]
name = "sol_drip"
version = "0.1.0"
edition = "2021"
description = "A CLI tool for periodically fetching Solana airdrops"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
solana-client = "2.0.9"
solana-sdk = "2.0.9"
